In [1]:
import torch

In [2]:
empty_tensor = torch.Tensor()
print(empty_tensor)

tensor([])


In [3]:
### tensors should have a standardized shape

In [4]:
t1 = torch.tensor(5.)
print(t1)

tensor(5.)


In [5]:
t1.dtype

torch.float32

In [6]:
t2 = torch.tensor([1,2,3,4])
print(t2)

tensor([1, 2, 3, 4])


In [7]:
t2[0].dtype

torch.int64

In [8]:
t3 = torch.tensor([[1,2,3], [2,3,4], [3,4,5]])
print(t3)

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])


In [9]:
t4 = torch.tensor([[[1,3,4], [1,2,3]], [[1,2,3], [2,3,4]]])
print(t4)

tensor([[[1, 3, 4],
         [1, 2, 3]],

        [[1, 2, 3],
         [2, 3, 4]]])


In [10]:
t4.shape

torch.Size([2, 2, 3])

In [11]:
### gradients
### only floats can be converted

In [12]:
t5 = torch.tensor(4.0, requires_grad=True)
print(t5)

tensor(4., requires_grad=True)
