In [1]:
import torch
import numpy as np

In [2]:
x_np = np.array([1.,2.,3.,4.])
w_np = np.array([3.,4.,2.,4.])

In [3]:
x = torch.from_numpy(x_np)
w = torch.tensor(w_np, requires_grad=True)

In [4]:
y = torch.dot(w,x)
y.backward()

In [5]:
print(w.grad)

tensor([1., 2., 3., 4.], dtype=torch.float64)


In [6]:
new_np_w = w.detach().numpy()
new_np_x = x.numpy()
print(new_np_w)
print(new_np_x)
print(type(new_np_w))

[3. 4. 2. 4.]
[1. 2. 3. 4.]
<class 'numpy.ndarray'>
